/* Copyright (c) 2013-2026 Jeffrey Pfau
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// Dev tool, not a test: runs affine-rom.h on a real GBA BIOS and prints
// bios-affine-golden.h. The BIOS itself is never committed.
//   usage: bios-affine-emit gba_bios.bin > src/gba/test/bios-affine-golden.h

#include "affine-rom.h"

#include <mgba/core/log.h>

#include <fcntl.h>
#include <stdio.h>

// The core logs to stdout by default, which is where the header goes.
static void _quiet(struct mLogger* logger, int category, enum mLogLevel level, const char* format, va_list args) {
	UNUSED(logger);
	UNUSED(category);
	UNUSED(level);
	UNUSED(format);
	UNUSED(args);
}

int main(int argc, char** argv) {
	if (argc < 2) {
		fprintf(stderr, "usage: %s gba_bios.bin\n", argv[0]);
		return 2;
	}
	static uint32_t rom[AFFINE_ROM_WORDS];
	static uint16_t out[AFFINE_OUT_HALFWORDS];
	struct mLogger logger = { .log = _quiet };
	mLogSetDefaultLogger(&logger);
	affineBuildRom(rom);

	struct mCore* core = GBACoreCreate();
	core->init(core);
	mCoreInitConfig(core, NULL);
	core->loadROM(core, VFileFromConstMemory(rom, sizeof(rom)));
	struct VFile* bios = VFileOpen(argv[1], O_RDONLY);
	if (!bios || !core->loadBIOS(core, bios, 0)) {
		fprintf(stderr, "cannot load BIOS %s\n", argv[1]);
		return 1;
	}
	core->reset(core);
	if (!((struct GBA*) core->board)->memory.fullBios || !affineRun(core, rom, out)) {
		fprintf(stderr, "real BIOS run failed\n");
		return 1;
	}

	printf("// Generated by src/gba/test/bios-affine-emit.c from a real GBA BIOS.\n");
	printf("// BgAffineSet then ObjAffineSet outputs for affine-rom.h's inputs.\n");
	printf("static const uint16_t affineGolden[%d] = {\n", AFFINE_OUT_HALFWORDS);
	int i;
	for (i = 0; i < AFFINE_OUT_HALFWORDS; ++i) {
		printf("%s0x%04X,%s", i % 12 ? " " : "\t", out[i], i % 12 == 11 ? "\n" : "");
	}
	printf("\n};\n");
	mCoreConfigDeinit(&core->config);
	core->deinit(core);
	return 0;
}
